name: Build and Test app
on: push
jobs:
  test:
    runs-on: macOS-latest
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_WORKSPACE: ${{ 'Reddit-reader.xcworkspace' }}
      XC_SCHEME: ${{ 'Reddit-reader' }}
    steps:
    - uses: actions/checkout@master
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.4.app
    - name: Install Dependencies
      run: |
        pod install --verbose
      shell: bash
    - name: Run Unit Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11' 

  - uses: ziishaned/jest-reporter-action@v0.0.1
  with:
  github-token: ${{ secrets.GITHUB_TOKEN }}
  test-command: "yarn jest --coverage"




  #     - name: Xcode Test
  # # You may pin to the exact commit or the version.
  # # uses: devbotsxyz/xcode-test@8f7f94ea653de78092a24ccc5cf6e3da59268d83
  # uses: devbotsxyz/xcode-test@v1.1.0
  # with:
  #   # Workspace
  #   workspace: # optional
  #   # Project
  #   project: # optional
  #   # Scheme
  #   scheme: # optional
  #   # Configuration
  #   configuration: # optional
  #   # Destination
  #   destination: # optional
  #   # SDK
  #   sdk: # optional
  #   # Architecture
  #   arch: # optional
  #   # Code sign identity
  #   code-sign-identity: # optional
  #   # Development team ID
  #   development-team: # optional
  #   # Path of the .xcresult bundle
  #   result-bundle-path: # optional
  #   # Name of uploaded .xcresult artifact
  #   result-bundle-name: # optional, default is Test Results
  #   # What tests to run or skip
  #   constraints: # optional
  #   # The ISO 3166-1 region in which to run the tests
  #   region: # optional
  #   # The ISO 639-1 language in which to run the tests
  #   language: # optional
  #   # The locale identifier ([language]_[region]) in which to run the tests
  #   locale: # optional

   