name: Build and Test app
on: push
jobs:
  test:
    runs-on: macOS-latest
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_WORKSPACE: ${{ 'Reddit-reader.xcworkspace' }}
      XC_SCHEME: ${{ 'Reddit-reader' }}
    steps:
    - uses: actions/checkout@master
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.4.app
    - name: Install Dependencies
      run: |
        pod install --verbose
      shell: bash
    - name: Run Unit Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11' 
   - name: Install Slather
      run: gem install slather
      
   - name: Slather test report
      run: slather coverage
    
   - uses: manivelnagarajan/cobertura-report-slather@master
      with:
          path: Coverage/cobertura.xml
          report_name: Freshdesk iOS Code Coverage Report
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 30
          ignore_branch_rate: true
          only_changed_files: true
